[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
skip_glob = [".env/*"]

[tool.black]
line-length = 88 # default is 88
target-version = ['py39', 'py310', 'py311']

[tool.pytest.ini_options]
pythonpath = ["."]